export const locationItems = [
    // Kerala
    { label: "Munnar, Kerala", value: "Munnar, Kerala" },
    { label: "Alleppey, Kerala", value: "Alleppey, Kerala" },
    { label: "Kochi, Kerala", value: "Kochi, Kerala" },
    { label: "Kovalam, Kerala", value: "Kovalam, Kerala" },
    { label: "Wayanad, Kerala", value: "Wayanad, Kerala" },
    { label: "Thekkady, Kerala", value: "Thekkady, Kerala" },
    { label: "Varkala, Kerala", value: "Varkala, Kerala" },
    { label: "Trivandrum, Kerala", value: "Trivandrum, Kerala" },
    { label: "Kumarakom, Kerala", value: "Kumarakom, Kerala" },
    { label: "Thrissur, Kerala", value: "Thrissur, Kerala" },
    { label: "Bekal, Kerala", value: "Bekal, Kerala" },
    { label: "Palakkad, Kerala", value: "Palakkad, Kerala" },
    { label: "Muthanga Wildlife Sanctuary, Kerala", value: "Muthanga Wildlife Sanctuary, Kerala" },
    { label: "Sabarimala, Kerala", value: "Sabarimala, Kerala" },
    { label: "Kollam, Kerala", value: "Kollam, Kerala" },
    { label: "Kannur, Kerala", value: "Kannur, Kerala" },
    { label: "Kasaragod, Kerala", value: "Kasaragod, Kerala" },
    { label: "Kozhikode, Kerala", value: "Kozhikode, Kerala" },
    { label: "Pathanamthitta, Kerala", value: "Pathanamthitta, Kerala" },
    { label: "Ernakulam, Kerala", value: "Ernakulam, Kerala" },
    { label: "Idukki, Kerala", value: "Idukki, Kerala" },

    // Karnataka
    { label: "Coorg, Karnataka", value: "Coorg, Karnataka" },
    { label: "Hampi, Karnataka", value: "Hampi, Karnataka" },
    { label: "Gokarna, Karnataka", value: "Gokarna, Karnataka" },
    { label: "Jog Falls, Karnataka", value: "Jog Falls, Karnataka" },
    { label: "Bangalore, Karnataka", value: "Bangalore, Karnataka" },
    { label: "Kabini, Karnataka", value: "Kabini, Karnataka" },
    { label: "Bandipur National Park, Karnataka", value: "Bandipur National Park, Karnataka" },
    { label: "Chikmagalur, Karnataka", value: "Chikmagalur, Karnataka" },
    { label: "Mysore, Karnataka", value: "Mysore, Karnataka" },
    { label: "Madikeri, Karnataka", value: "Madikeri, Karnataka" },
    { label: "Bijapur, Karnataka", value: "Bijapur, Karnataka" },
    { label: "Dandeli, Karnataka", value: "Dandeli, Karnataka" },
    { label: "Shivanasamundram, Karnataka", value: "Shivanasamundram, Karnataka" },
    { label: "Nagarhole, Karnataka", value: "Nagarhole, Karnataka" },
    { label: "Kudremukh, Karnataka", value: "Kudremukh, Karnataka" },
    { label: "Shimoga, Karnataka", value: "Shimoga, Karnataka" },
    { label: "Mantralyam, Karnataka", value: "Mantralyam, Karnataka" },
    { label: "Anthargange, Karnataka", value: "Anthargange, Karnataka" },
    { label: "Murudeshwar, Karnataka", value: "Murudeshwar, Karnataka" },
    { label: "Pattadakal, Karnataka", value: "Pattadakal, Karnataka" },
    { label: "Udupi, Karnataka", value: "Udupi, Karnataka" },
    { label: "Maravantha, Karnataka", value: "Maravantha, Karnataka" },

    // Tamil Nadu
    { label: "Ooty, Tamilnadu", value: "Ooty, Tamilnadu" },
    { label: "Kanyakumari, Tamilnadu", value: "Kanyakumari, Tamilnadu" },
    { label: "Kodaikanal, Tamilnadu", value: "Kodaikanal, Tamilnadu" },
    { label: "Madurai, Tamilnadu", value: "Madurai, Tamilnadu" },
    { label: "Rameswaram, Tamilnadu", value: "Rameswaram, Tamilnadu" },
    { label: "Thanjevur, Tamilnadu", value: "Thanjevur, Tamilnadu" },
    { label: "Mahabalipuram, Tamilnadu", value: "Mahabalipuram, Tamilnadu" },
    { label: "Kanchipuram, Tamilnadu", value: "Kanchipuram, Tamilnadu" },
    { label: "Chennai, Tamilnadu", value: "Chennai, Tamilnadu" },
    { label: "Yercaud, Tamilnadu", value: "Yercaud, Tamilnadu" },
    { label: "Coonoor, Tamilnadu", value: "Coonoor, Tamilnadu" },
    { label: "Hongenakkal, Tamilnadu", value: "Hongenakkal, Tamilnadu" },
    { label: "Coimbatore, Tamilnadu", value: "Coimbatore, Tamilnadu" },
    { label: "Chidambatam, Tamilnadu", value: "Chidambatam, Tamilnadu" },

    // Andhra Pradesh
    { label: "Tirupati, Andhra Pradesh", value: "Tirupati, Andhra Pradesh" },
    { label: "Hyderabad, Andhra Pradesh", value: "Hyderabad, Andhra Pradesh" },
    { label: "Araku Valley, Andhra Pradesh", value: "Araku Valley, Andhra Pradesh" },
    { label: "Papi Kondalu, Andhra Pradesh", value: "Papi Kondalu, Andhra Pradesh" },
    { label: "Belum Caves, Andhra Pradesh", value: "Belum Caves, Andhra Pradesh" },
    { label: "Visakhapatnam, Andhra Pradesh", value: "Visakhapatnam, Andhra Pradesh" },
    { label: "Srisailam, Andhra Pradesh", value: "Srisailam, Andhra Pradesh" },
    { label: "Warangal, Andhra Pradesh", value: "Warangal, Andhra Pradesh" },
    { label: "Lepakshi, Andhra Pradesh", value: "Lepakshi, Andhra Pradesh" },
    { label: "Borra Caves, Andhra Pradesh", value: "Borra Caves, Andhra Pradesh" },
    { label: "Vijayawada, Andhra Pradesh", value: "Vijayawada, Andhra Pradesh" },
    { label: "Horsley Hills, Andhra Pradesh", value: "Horsley Hills, Andhra Pradesh" },
    { label: "Amaravati, Andhra Pradesh", value: "Amaravati, Andhra Pradesh" },
    { label: "Vizag, Andhra Pradesh", value: "Vizag, Andhra Pradesh" },

    // Other
    { label: "Pondicherry", value: "Pondicherry" },
    { label: "Andaman & Nicobar", value: "Andaman & Nicobar" },
    { label: "Goa", value: "Goa" },
    { label: "Lakshadweep", value: "Lakshadweep" },
    { label: "Auroville, Pondicherry", value: "Auroville, Pondicherry" },
    { label: "Adilabad, Telangana", value: "Adilabad, Telangana" },
];

export const methodItems = [
    { label: "Phone", value: "Phone" },
    { label: "Email", value: "Email" },
    { label: "WhatsApp", value: "WhatsApp" },
];
export const daysItems = [
    { label: "2 Days 1 Night", value: "2 Day 1 Night" },
    { label: "3 Days 2 Nights", value: "3 Day 2 Night" },
    { label: "4 Days 3 Nights", value: "4 Day 3 Night" },
    { label: "5 Days 4 Nights", value: "5 Day 4 Night" },
    { label: "6 Days 5 Nights", value: "6 Day 5 Night" },
    { label: "7 Days 6 Nights", value: "7 Day 6 Night" },
    { label: "8 Days 7 Nights", value: "8 Day 7 Night" },
];
export const vehicleItems = [
    { label: "Toyota Etios", value: "Toyota Etios" },
    { label: "Toyota Innova A/C", value: "Toyota Innova A/C" },
    { label: "Toyota Innova Crysta", value: "Toyota Innova Crysta" },
    { label: "Corolla - A/C", value: "Corolla - A/C" },
    { label: "Toyota Fortuner", value: "Toyota Fortuner" },
    { label: "Camery, Accord - A/C", value: "Camery, Accord - A/C" },
    { label: "Benz E Class - A/C", value: "Benz E Class - A/C" },
    { label: "Benz S Class - A/C", value: "Benz S Class - A/C" },
    { label: "BMW 5 Series - A/C", value: "BMW 5 Series - A/C" },
    { label: "BMW 7 Series - A/C", value: "BMW 7 Series - A/C" },
    { label: "TT - NON A/C", value: "TT - NON A/C" },
    { label: "TT - A/C", value: "TT - A/C" },
];
export const languageItems = [
    { label: "Yes", value: "Yes" },
    { label: "No", value: "No" },
];

export const activityItems = [
    { label: "Sightseeing", value: "Sightseeing" },
    { label: "Adventure", value: "Adventure" },
    { label: "Sports", value: "Sports" },
    { label: "Cultural Tours", value: "Cultural Tours" },
    { label: "Beach Relaxation", value: "Beach Relaxation" },
    { label: "Shopping", value: "Shopping" },
];

export const dayTourLocationItems = [
    { label: "Thiruvananthapuram", value: "Thiruvananthapuram" },
    { label: "Kollam", value: "Kollam" },
    { label: "Pathanamthitta", value: "Pathanamthitta" },
    { label: "Alappuzha", value: "Alappuzha" },
    { label: "Kottayam", value: "Kottayam" },
    { label: "Idukki", value: "Idukki" },
    { label: "Ernakulam", value: "Ernakulam" },
    { label: "Thrissur", value: "Thrissur" },
    { label: "Palakkad", value: "Palakkad" },
    { label: "Malappuram", value: "Malappuram" },
    { label: "Kozhikode", value: "Kozhikode" },
    { label: "Wayanad", value: "Wayanad" },
    { label: "Kannur", value: "Kannur" },
    { label: "Kasaragod", value: "Kasaragod" },
];
